CREATE TABLE cx_cvciq_v3.bi_cvc_agenda (
  "ID" NUMBER,
  entry_date DATE,
  cvc_request_id NUMBER(15),
  bi_request_id NUMBER(15),
  request_activity_day_id NUMBER,
  request_type_activity_id NUMBER,
  company_name VARCHAR2(100 CHAR),
  entry_type VARCHAR2(20 CHAR),
  entry_name VARCHAR2(100 CHAR),
  topic_id NUMBER,
  catering_id NUMBER,
  no_attendees NUMBER,
  opp_number VARCHAR2(100 CHAR),
  agenda_topic_id NUMBER,
  topic_objective CLOB,
  optional_topic VARCHAR2(4000 CHAR),
  catering_type VARCHAR2(150 CHAR),
  other_dietary_opt VARCHAR2(300 CHAR),
  special_instruction VARCHAR2(4000 CHAR),
  special_dietary VARCHAR2(200 CHAR),
  entry_day NUMBER,
  time_from DATE,
  time_to DATE,
  location_id NUMBER,
  room_id NUMBER,
  created_by VARCHAR2(80 CHAR) NOT NULL,
  created_date DATE NOT NULL,
  updated_by VARCHAR2(80 CHAR),
  updated_date DATE,
  room_main VARCHAR2(5 CHAR),
  duration NUMBER,
  process_flag VARCHAR2(5 BYTE),
  digital_signage VARCHAR2(255 BYTE),
  req_pr_flag VARCHAR2(20 BYTE),
  pick_main_room NUMBER
);