CREATE TABLE cx_cvciq_v3.bi_req_cat_act_stage (
  "ID" NUMBER NOT NULL,
  request_activity_day_id NUMBER,
  duration NUMBER,
  room NUMBER,
  request_type_activity_id NUMBER,
  catering_type VARCHAR2(256 BYTE),
  no_of_attendees NUMBER,
  diet_information VARCHAR2(256 BYTE),
  notes VARCHAR2(4000 BYTE),
  unique_id VARCHAR2(256 BYTE),
  tenant_id NUMBER,
  created_by VARCHAR2(256 BYTE),
  created_ts TIMESTAMP,
  updated_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP,
  "VERSION" NUMBER,
  attribute_info VARCHAR2(20 BYTE),
  activity_start_time TIMESTAMP,
  request_id NUMBER,
  activity_date DATE
);