CREATE TABLE cx_cvciq_v3.bi_request (
  "ID" NUMBER NOT NULL,
  request_type_id NUMBER,
  location_id NUMBER,
  requestor NUMBER CONSTRAINT bi_request_requestor_chk CHECK ("REQUESTOR" IS NOT NULL),
  sales_division VARCHAR2(256 BYTE),
  opportunity_status VARCHAR2(256 BYTE),
  opened_date DATE,
  closed_date DATE,
  start_date DATE,
  duration NUMBER,
  alternative_date DATE,
  host_name VARCHAR2(256 BYTE),
  host_contact VARCHAR2(256 BYTE),
  no_of_break_rooms NUMBER,
  effort_level NUMBER,
  briefing_manager NUMBER,
  customer_name VARCHAR2(256 BYTE),
  customer_website VARCHAR2(256 BYTE),
  country VARCHAR2(256 BYTE),
  industry VARCHAR2(256 BYTE),
  visit_focus VARCHAR2(256 BYTE),
  created_by VARCHAR2(256 BYTE),
  updated_by VARCHAR2(256 BYTE),
  status VARCHAR2(256 BYTE),
  tenant_id NUMBER,
  dress_code VARCHAR2(200 BYTE),
  gift_type VARCHAR2(256 BYTE),
  no_of_gifts NUMBER(*,0),
  unique_id VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  "STATE" VARCHAR2(30 BYTE),
  schedular NUMBER,
  edr_choice VARCHAR2(60 BYTE),
  heading_for_menu VARCHAR2(100 BYTE),
  special_items CHAR,
  attending_executive VARCHAR2(60 BYTE),
  "ORGANIZATION" VARCHAR2(256 BYTE),
  main_room NUMBER,
  digital_signage_required CHAR,
  is_template CHAR,
  notes VARCHAR2(4000 BYTE),
  digital_signage_option VARCHAR2(60 BYTE),
  expected_no_of_ext_attendees NUMBER DEFAULT 1,
  expected_no_of_int_attendees NUMBER DEFAULT 1,
  briefing_document VARCHAR2(400 BYTE),
  host_email VARCHAR2(100 BYTE),
  is_date_confirmed CHAR,
  visit_objective VARCHAR2(4000 BYTE),
  desired_outcome VARCHAR2(4000 BYTE),
  oppurtunity_size VARCHAR2(4000 BYTE) DEFAULT 0,
  cust_current_initiatives VARCHAR2(4000 BYTE),
  sensitive_issues VARCHAR2(4000 BYTE),
  competitors VARCHAR2(4000 BYTE),
  business_case VARCHAR2(4000 BYTE),
  closed_revenue NUMBER,
  visit_summary VARCHAR2(4000 BYTE),
  cost_center VARCHAR2(256 BYTE),
  visit_type VARCHAR2(256 BYTE),
  tenant_account_id NUMBER,
  customer_tier VARCHAR2(256 BYTE),
  created_ts TIMESTAMP,
  updated_ts TIMESTAMP,
  meeting_objective VARCHAR2(4000 BYTE),
  is_compliant CHAR,
  end_date DATE,
  osc_account_id VARCHAR2(256 BYTE),
  primary_opportunity_id VARCHAR2(256 BYTE),
  is_validated CHAR,
  account_name VARCHAR2(256 BYTE),
  is_delete_alert_shown CHAR,
  opportunity_revenue VARCHAR2(256 BYTE),
  opportunity_revenue_old NUMBER,
  closed_opportunity_revenue NUMBER,
  other_requirements CLOB,
  technical_requirements CLOB,
  host_business_title VARCHAR2(256 BYTE),
  CONSTRAINT bi_request_pk PRIMARY KEY ("ID"),
  CONSTRAINT bi_request_br_mngr_user_id_fk FOREIGN KEY (briefing_manager) REFERENCES cx_cvciq_v3.bi_user ("ID"),
  CONSTRAINT bi_request_location_id_fk FOREIGN KEY (location_id) REFERENCES cx_cvciq_v3.bi_location ("ID"),
  CONSTRAINT bi_request_main_room_loc_id_fk FOREIGN KEY (main_room) REFERENCES cx_cvciq_v3.bi_location ("ID"),
  CONSTRAINT bi_request_requestor_usr_id_fk FOREIGN KEY (requestor) REFERENCES cx_cvciq_v3.bi_user ("ID"),
  CONSTRAINT bi_request_req_typ_id_fk FOREIGN KEY (request_type_id) REFERENCES cx_cvciq_v3.bi_request_type ("ID"),
  CONSTRAINT bi_request_schedular_usr_id_fk FOREIGN KEY (schedular) REFERENCES cx_cvciq_v3.bi_user ("ID")
);