CREATE TABLE cx_cvciq_v3.bi_user_stage (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  first_name VARCHAR2(256 BYTE),
  middle_name VARCHAR2(256 BYTE),
  last_name VARCHAR2(256 BYTE),
  title VARCHAR2(256 BYTE),
  user_name VARCHAR2(256 BYTE),
  is_active CHAR(6 BYTE),
  tenant_id NUMBER,
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  color_code VARCHAR2(20 BYTE),
  CONSTRAINT bi_user_pk1 PRIMARY KEY ("ID"),
  CONSTRAINT bi_user_unique1 UNIQUE (user_name),
  CONSTRAINT bi_user_tenantid_fk1 FOREIGN KEY (tenant_id) REFERENCES cx_cvciq_v3.bi_tenant ("ID")
);