CREATE TABLE cx_cvciq_v3.t_cloud_session (
  "ID" NUMBER(11) NOT NULL,
  external_id VARCHAR2(128 BYTE),
  account_id NUMBER(11),
  session_token VARCHAR2(1024 BYTE),
  expires_at TIMESTAMP,
  client_type_id NUMBER(11),
  auth_code VARCHAR2(256 BYTE),
  auth_code_expires_at TIMESTAMP,
  redirect_uri VARCHAR2(256 BYTE),
  refresh_token_id NUMBER(11),
  created_at TIMESTAMP,
  created_by VARCHAR2(256 BYTE),
  modified_at TIMESTAMP,
  modified_by VARCHAR2(256 BYTE),
  oauth_session_id NUMBER(11),
  idx_token VARCHAR2(8 BYTE),
  setup_token VARCHAR2(64 BYTE),
  device_id NUMBER(11),
  CONSTRAINT t_cloud_session_pk PRIMARY KEY ("ID"),
  CONSTRAINT session_account FOREIGN KEY (account_id) REFERENCES cx_cvciq_v3.bi_user ("ID"),
  CONSTRAINT session_client_type FOREIGN KEY (client_type_id) REFERENCES cx_cvciq_v3.t_client_type ("ID"),
  CONSTRAINT session_oauth_provider FOREIGN KEY (oauth_session_id) REFERENCES cx_cvciq_v3.t_oauth_session ("ID"),
  CONSTRAINT session_refresh_token FOREIGN KEY (refresh_token_id) REFERENCES cx_cvciq_v3.t_cloud_refresh_token ("ID")
);