CREATE OR REPLACE PROCEDURE cx_cvciq_v3.master_ddl_setup2
IS

  BEGIN

		EXECUTE IMMEDIATE 'ALTER TABLE BI_LOCATION ADD LOCATION_ORDER NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_LOCATION_CALENDAR ADD ACTIVITY_DAY_ROOM_ID NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_LOOKUP_VALUE ADD SORT_ORDER NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_LOOKUP_VALUE ADD CRITERIA VARCHAR(256)';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_NOTE ADD NOTE_START_DATE DATE';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_NOTE ADD NOTE_END_DATE DATE';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST ADD END_DATE DATE';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST ADD OSC_ACCOUNT_ID NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST ADD PRIMARY_OPPORTUNITY_ID VARCHAR(256)';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST_ATTENDEES ADD IS_TRANSLATOR CHAR(1)';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST_PRESENTER ADD PRESENTER_ORDER NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST_OPPORTUNITY ADD IS_PRIMARY CHAR(1)';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_REQUEST_TOPIC_ACTIVITY ADD MRM_PRODUCT_ID NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_TOPIC ADD MRM_PRODUCT_ID NUMBER';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_TOPIC ADD LAST_REFRESH_DATE DATE';
		EXECUTE IMMEDIATE 'ALTER TABLE BI_TOPIC ADD MRM_PRODUCT_NAME VARCHAR2(1000 BYTE)';



		--------------------------------------------------------
		--  DDL for Table BI_LOCATION_PARAMETER
		--------------------------------------------------------


		  EXECUTE IMMEDIATE 'CREATE TABLE "BI_LOCATION_PARAMETER"  ("ID" NUMBER, "UNIQUE_ID" VARCHAR2(250 BYTE), "LOCATION_ID" NUMBER, "CREATED_BY" VARCHAR2(256 BYTE), "CREATED_TS" TIMESTAMP (6), "UPDATED_BY" VARCHAR2(256 BYTE),"UPDATED_TS" TIMESTAMP (6),	"TENANT_ID" NUMBER,	"VERSION" NUMBER,"IS_ACTIVE" CHAR(1 BYTE), "PARAM_NAME" VARCHAR2(256 BYTE), "PARAM_DISPLAY_TEXT" VARCHAR2(1000 BYTE),"PARAM_VALUE" VARCHAR2(2000 BYTE), "PARAM_DESCRIPTION" VARCHAR2(2000 BYTE), "PARAM_TYPE" VARCHAR2(256 BYTE),"PARAM_VALIDATION" VARCHAR2(2000 BYTE),"PARAM_DISPLAY_TYPE" VARCHAR2(256 BYTE), "IS_REQUIRED" CHAR(1 BYTE),"IS_MODIFIABLE" CHAR(1 BYTE) )';
		--------------------------------------------------------
		--  DDL for Index BI_LOCATION_PARAMETER_PK
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_LOCATION_PARAMETER_PK" ON "BI_LOCATION_PARAMETER" ("ID")';
		--------------------------------------------------------
		--  Constraints for Table BI_LOCATION_PARAMETER
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_LOCATION_PARAMETER" ADD CONSTRAINT "BI_LOCATION_PARAMETER_PK" PRIMARY KEY ("ID")';
		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_LOCATION_PARAMETER" MODIFY ("ID" NOT NULL ENABLE)';
		--------------------------------------------------------
		--  Ref Constraints for Table BI_LOCATION_PARAMETER
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_LOCATION_PARAMETER" ADD CONSTRAINT "BI_LOCATION_PARAMETER_FK1" FOREIGN KEY ("LOCATION_ID")
			  REFERENCES "BI_LOCATION" ("ID") ENABLE';

           EXECUTE IMMEDIATE 'CREATE SEQUENCE   "BI_LOCATION_PARAMETER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ';


			  --------------------------------------------------------
		--  DDL for Table BI_REQUEST_ACT_DAY_ROOM
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'CREATE TABLE "BI_REQUEST_ACT_DAY_ROOM" (	"ID" NUMBER, "REQUEST_ACTIVITY_DAY_ID" NUMBER, "ROOM" NUMBER,"ROOM_TYPE" VARCHAR2(256 BYTE), "START_TIME" TIMESTAMP (6), "END_TIME" TIMESTAMP (6), "UNIQUE_ID" VARCHAR2(256 BYTE),"TENANT_ID" NUMBER, "VERSION" NUMBER, "CREATED_BY" VARCHAR2(256 BYTE),"CREATED_TS" TIMESTAMP (6), "UPDATED_BY" VARCHAR2(256 BYTE),"UPDATED_TS" TIMESTAMP (6),	"REQUEST_ID" NUMBER )';
		--------------------------------------------------------
		--  DDL for Index BI_REQUEST_ACT_DAY_ROOM_UK
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_REQUEST_ACT_DAY_ROOM_UK" ON "BI_REQUEST_ACT_DAY_ROOM" ("REQUEST_ACTIVITY_DAY_ID", "ROOM") ';
		  
		--------------------------------------------------------
		--  DDL for Index BI_REQUEST_ACT_DAY_ROOM_PK
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_REQUEST_ACT_DAY_ROOM_PK" ON "BI_REQUEST_ACT_DAY_ROOM" ("ID") ';
		--------------------------------------------------------
		--  Constraints for Table BI_REQUEST_ACT_DAY_ROOM
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACT_DAY_ROOM" ADD CONSTRAINT "BI_REQUEST_ACT_DAY_ROOM_UK" UNIQUE ("REQUEST_ACTIVITY_DAY_ID", "ROOM")';
		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACT_DAY_ROOM" ADD CONSTRAINT "BI_REQUEST_ACT_DAY_ROOM_PK" PRIMARY KEY ("ID")';
		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACT_DAY_ROOM" MODIFY ("ID" NOT NULL ENABLE)';
		--------------------------------------------------------
		--  Ref Constraints for Table BI_REQUEST_ACT_DAY_ROOM
		--------------------------------------------------------

                 EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACTIVITY_DAY" ADD CONSTRAINT "BI_REQUEST_ACTIVITY_DAY_PK" PRIMARY KEY ("ID")';

		   EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACT_DAY_ROOM" ADD CONSTRAINT "BI_REQUEST_ACT_DAY_ROOM_FK" FOREIGN KEY ("REQUEST_ACTIVITY_DAY_ID") REFERENCES "BI_REQUEST_ACTIVITY_DAY" ("ID") ENABLE';
		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACT_DAY_ROOM" ADD CONSTRAINT "BI_REQUEST_ACT_LOCATION_FK" FOREIGN KEY ("ROOM") REFERENCES "BI_LOCATION" ("ID") ENABLE';
		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_ACT_DAY_ROOM" ADD CONSTRAINT "BI_REQUEST_ROOM_REQ_FK" FOREIGN KEY ("REQUEST_ID") REFERENCES "BI_REQUEST" ("ID") ENABLE';

			  
		--------------------------------------------------------
		--  DDL for Table BI_REQUEST_TECHNICAL_DETAIL
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'CREATE TABLE "BI_REQUEST_TECHNICAL_DETAIL" ("ID" NUMBER, "UNIQUE_ID" VARCHAR2(256 BYTE), "TENANT_ID" NUMBER, "CREATED_BY" VARCHAR2(256 BYTE),"UPDATED_BY" VARCHAR2(256 BYTE),"VERSION" NUMBER, "CREATED_TS" TIMESTAMP (6), "UPDATED_TS" TIMESTAMP (6),"REQUEST_ID" NUMBER,"ITEM" VARCHAR2(256 BYTE), "REQUIREMENT" CLOB,"REQUIREMENT_DETAIL" CLOB ) ';
		--------------------------------------------------------
		--  DDL for Index BI_REQUEST_TECHNICAL_DETAI_PK
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_REQUEST_TECHNICAL_DETAIL_PK" ON "BI_REQUEST_TECHNICAL_DETAIL" ("ID") ';
		--------------------------------------------------------
		--  Constraints for Table BI_REQUEST_TECHNICAL_DETAIL
		--------------------------------------------------------

		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_TECHNICAL_DETAIL" ADD CONSTRAINT "BI_REQUEST_TECHNICAL_DETAI_PK" PRIMARY KEY ("ID")';
		  EXECUTE IMMEDIATE 'ALTER TABLE "BI_REQUEST_TECHNICAL_DETAIL" MODIFY ("ID" NOT NULL ENABLE)';

           EXECUTE IMMEDIATE 'CREATE SEQUENCE   "BI_REQ_TECH_DETAIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ';
		

 EXECUTE IMMEDIATE 'CREATE TABLE "BI_CXD_DATA" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"REQUEST_ID" NUMBER, 
	"JSON_DATA" VARCHAR2(4000 BYTE), 
	"UNIQUE_ID" VARCHAR2(256 BYTE), 
	"TENANT_ID" NUMBER, 
	"VERSION" NUMBER(20,0), 
	"CREATED_BY" VARCHAR2(256 BYTE), 
	"CREATED_TS" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(256 BYTE), 
	"UPDATED_TS" TIMESTAMP (6), 
	"IS_ACTIVE" CHAR(256 BYTE), 
	 CONSTRAINT "BI_CXD_DATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "BI_CXD_DATA_REQUEST_FK" FOREIGN KEY ("REQUEST_ID")
	  REFERENCES"BI_REQUEST" ("ID") ENABLE, 
	 CONSTRAINT "BI_CXD_DATA_TENANT_FK" FOREIGN KEY ("TENANT_ID")
	  REFERENCES "BI_TENANT" ("ID") ENABLE)';

      EXECUTE IMMEDIATE 'CREATE SEQUENCE   "BI_CXD_DATA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE NOPARTITION';    
	  
END ;
/