CREATE OR REPLACE PROCEDURE cx_cvciq_v3."MASTER_DDL_SETUP1" 
IS

BEGIN


	  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_ASSET_DETAIL_UNIQUE" ON "BI_ASSET_DETAIL" ("NAME", "ASSET_MASTER_ID", "LOCATION_ID")';	  
	  EXECUTE IMMEDIATE 'ALTER TABLE "BI_ASSET_DETAIL" ADD CONSTRAINT "BI_ASSET_DETAIL_UNIQUE" UNIQUE ("NAME", "ASSET_MASTER_ID", "LOCATION_ID")';
	  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_EVENT_NOTIFICATION_UK1" ON "BI_EVENT_NOTIFICATION" ("REQUEST_TYPE_ID", "TARGET_STATE", "LOCATION_ID")' ;	  
	  EXECUTE IMMEDIATE 'ALTER TABLE "BI_EVENT_NOTIFICATION" ADD CONSTRAINT "BI_EVENT_NOTIFICATION_UK1" UNIQUE ("REQUEST_TYPE_ID", "TARGET_STATE", "LOCATION_ID")';
	  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_LOOKUP_VALUE_UNIQUE" ON "BI_LOOKUP_VALUE" ("VALUE", "PARENT_ID", "LOOKUP_TYPE_ID", "LOCATION_ID")'  ;	  
	  EXECUTE IMMEDIATE 'ALTER TABLE "BI_LOOKUP_VALUE" ADD CONSTRAINT "BI_LOOKUP_VALUE_UNIQUE" UNIQUE ("VALUE", "PARENT_ID", "LOOKUP_TYPE_ID", "LOCATION_ID") ';	  
	  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_TEMPLATE_DETAIL_UNIQUE" ON "BI_TEMPLATE_DETAIL" ("TEMPLATE_MASTER_ID", "NAME") ' ;
	  EXECUTE IMMEDIATE 'ALTER TABLE "BI_TEMPLATE_DETAIL" ADD CONSTRAINT "BI_TEMPLATE_DETAIL_UNIQUE" UNIQUE ("TEMPLATE_MASTER_ID", "NAME") ';
	  EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX "BI_TOPIC_UNIQUE" ON "BI_TOPIC" ("TOPIC_TYPE_ID", "NAME", "PARENT_ID", "LOCATION_ID") ';	  
	  EXECUTE IMMEDIATE 'ALTER TABLE "BI_TOPIC" ADD CONSTRAINT "BI_TOPIC_UNIQUE" UNIQUE ("TOPIC_TYPE_ID", "NAME", "PARENT_ID", "LOCATION_ID") ';


          EXECUTE IMMEDIATE 'ALTER TABLE "BI_LOCATION_USER" ADD CONSTRAINT "BI_LOCATION_USER_PK" PRIMARY KEY ("ID")';

          EXECUTE IMMEDIATE 'ALTER TABLE BI_LOCATION_USER ADD CONSTRAINT BI_LOCATION_USER_FK1 FOREIGN KEY (USER_ID)
REFERENCES BI_USER (ID) ENABLE';

END ;
/