CREATE OR REPLACE TRIGGER cx_cvciq_v3."BI_ASSET_DETAIL_TRIGGER" 
 BEFORE INSERT ON cx_cvciq_v3.BI_ASSET_DETAIL
 FOR EACH ROW
DISABLE BEGIN
 SELECT BI_ASSET_DETAIL_SEQ.NEXTVAL
 INTO :new.id
 FROM dual;
END;
/