CREATE OR REPLACE TRIGGER cx_cvciq_v3."BI_EVENT_NOTIFICATION_TRIGGER"
BEFORE INSERT ON cx_cvciq_v3.BI_EVENT_NOTIFICATION
FOR EACH ROW
BEGIN
SELECT BI_EVENT_NOTIFICATION_SEQ.NEXTVAL
INTO :new.id
FROM dual;
END;
/