CREATE OR REPLACE FORCE VIEW cx_cvciq_v3.vw_cvc_location (address,agenda_display,catering,city,contact_us,country,created_by,created_date,email_from,hotel,"HYBRID","ID",loc_type,"NAME","ORGANIZATION",request_time,req_can_be_ac,req_can_book_rooms,room_setup,saturday,self_service,special_days,"STATE",sunday,technical_setup,timezone,time_from,time_to,transportation,updated_by,updated_date,used_in_edr) AS
SELECT ADDRESS,
AGENDA_DISPLAY,
CATERING,
CITY,
CONTACT_US,
COUNTRY,
CREATED_BY,
CREATED_DATE,
EMAIL_FROM,
HOTEL,
HYBRID,
ID,
LOC_TYPE,
NAME,
ORGANIZATION,
REQUEST_TIME,
REQ_CAN_BE_AC,
REQ_CAN_BOOK_ROOMS,
ROOM_SETUP,
SATURDAY,
SELF_SERVICE,
SPECIAL_DAYS,
STATE,
SUNDAY,
TECHNICAL_SETUP,
TIMEZONE,
TIME_FROM,
TIME_TO,
TRANSPORTATION,
UPDATED_BY,
UPDATED_DATE,
USED_IN_EDR FROM cx_cvc.CVC_LOCATION;