CREATE TABLE cx_cvciq_v3.bi_asset_detail (
  "ID" NUMBER,
  unique_id VARCHAR2(256 BYTE),
  uri VARCHAR2(256 BYTE),
  tenant_id NUMBER,
  asset_master_id NUMBER,
  active_from TIMESTAMP,
  active_to TIMESTAMP,
  is_active CHAR(256 BYTE),
  created_ts TIMESTAMP,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  "NAME" VARCHAR2(256 BYTE),
  description VARCHAR2(256 BYTE),
  location_id NUMBER,
  idx_token VARCHAR2(8 BYTE),
  CONSTRAINT bi_asset_detail_unique UNIQUE ("NAME",asset_master_id,location_id),
  CONSTRAINT bi_asset_detail_location_fk FOREIGN KEY (location_id) REFERENCES cx_cvciq_v3.bi_location ("ID"),
  CONSTRAINT bi_asset_detail_tenant_id_fk FOREIGN KEY (tenant_id) REFERENCES cx_cvciq_v3.bi_tenant ("ID")
);