CREATE TABLE cx_cvciq_v3.bi_lookup_value (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  code VARCHAR2(256 BYTE),
  "VALUE" VARCHAR2(256 BYTE),
  parent_id NUMBER,
  is_active CHAR(6 BYTE) DEFAULT '1',
  active_from TIMESTAMP WITH LOCAL TIME ZONE,
  active_to TIMESTAMP WITH LOCAL TIME ZONE,
  tenant_id NUMBER,
  lookup_type_id NUMBER,
  created_by VARCHAR2(256 BYTE),
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  "VERSION" NUMBER,
  location_id NUMBER,
  sort_order NUMBER,
  criteria VARCHAR2(256 BYTE),
  display_type VARCHAR2(256 BYTE),
  CONSTRAINT bi_lookup_value_pk PRIMARY KEY ("ID"),
  CONSTRAINT bi_lookup_value_unique UNIQUE ("VALUE",parent_id,lookup_type_id,location_id),
  CONSTRAINT bi_lookupvalue_lookuptype_fk FOREIGN KEY (lookup_type_id) REFERENCES cx_cvciq_v3.bi_lookup_type ("ID"),
  CONSTRAINT bi_lookup_value_id_fk FOREIGN KEY (parent_id) REFERENCES cx_cvciq_v3.bi_lookup_value ("ID"),
  CONSTRAINT bi_lookup_value_location_fk FOREIGN KEY (location_id) REFERENCES cx_cvciq_v3.bi_location ("ID"),
  CONSTRAINT bi_lookup_value_tenantid_fk FOREIGN KEY (tenant_id) REFERENCES cx_cvciq_v3.bi_tenant ("ID")
);