CREATE TABLE cx_cvciq_v3.bi_location (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  active_from DATE,
  active_to DATE,
  location_type_id NUMBER,
  address1 VARCHAR2(256 BYTE),
  address2 VARCHAR2(256 BYTE),
  city VARCHAR2(256 BYTE),
  "STATE" VARCHAR2(256 BYTE),
  contact_email VARCHAR2(256 BYTE),
  contact_name VARCHAR2(256 BYTE),
  contact_phone VARCHAR2(256 BYTE),
  code VARCHAR2(256 BYTE),
  "CAPACITY" NUMBER,
  zipcode VARCHAR2(256 BYTE),
  additional_info VARCHAR2(4000 BYTE),
  parent_id NUMBER,
  is_private CHAR(256 BYTE),
  is_assignable CHAR(256 BYTE),
  repository VARCHAR2(256 BYTE),
  asset_detail_id NUMBER,
  tenant_id NUMBER,
  created_by VARCHAR2(256 BYTE),
  created_ts TIMESTAMP,
  updated_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP,
  "VERSION" NUMBER,
  is_active CHAR(256 BYTE),
  country VARCHAR2(256 BYTE),
  "NAME" VARCHAR2(256 BYTE),
  location_timezone VARCHAR2(256 BYTE),
  location_latitude VARCHAR2(256 BYTE),
  location_longitude VARCHAR2(256 BYTE),
  location_order NUMBER,
  location_timezone_db VARCHAR2(100 BYTE),
  CONSTRAINT bi_location_pk PRIMARY KEY ("ID")
);