CREATE TABLE cx_cvciq_v3.bi_mrm_product_details_osc (
  "ID" NUMBER NOT NULL,
  product_id NUMBER,
  product_name VARCHAR2(1000 BYTE),
  product_class VARCHAR2(1000 BYTE),
  product_line VARCHAR2(1000 BYTE),
  product_group VARCHAR2(1000 BYTE),
  osc_product_status VARCHAR2(1000 BYTE),
  unique_id VARCHAR2(250 BYTE),
  created_by VARCHAR2(256 BYTE),
  created_ts TIMESTAMP,
  updated_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP,
  tenant_id NUMBER,
  "VERSION" NUMBER,
  is_active CHAR,
  product_level VARCHAR2(1000 BYTE),
  product_pillar VARCHAR2(1000 BYTE),
  mrm_product_status VARCHAR2(1000 BYTE),
  marketable_flag VARCHAR2(1000 BYTE),
  start_date TIMESTAMP WITH TIME ZONE,
  end_date TIMESTAMP WITH TIME ZONE,
  replacement_product VARCHAR2(1000 BYTE),
  response_channel VARCHAR2(1000 BYTE),
  admin_notes VARCHAR2(1000 BYTE),
  gtm_propername VARCHAR2(1000 BYTE),
  gtmapp_family VARCHAR2(1000 BYTE),
  gtmucm_tier1 VARCHAR2(1000 BYTE),
  gtmucm_tier2 VARCHAR2(1000 BYTE),
  gtmold_name VARCHAR2(1000 BYTE),
  wordmap_parentid VARCHAR2(1000 BYTE),
  wordmap_wordsetid VARCHAR2(1000 BYTE),
  wordmap_phrasetxt VARCHAR2(1000 BYTE),
  product_owned VARCHAR2(1000 BYTE),
  account_flags VARCHAR2(1000 BYTE),
  paid_searchwords VARCHAR2(1000 BYTE),
  arpr_keywords VARCHAR2(1000 BYTE),
  topic_scoring VARCHAR2(1000 BYTE),
  salescal_category1 VARCHAR2(1000 BYTE),
  salescal_category2 VARCHAR2(1000 BYTE),
  creation_date TIMESTAMP WITH TIME ZONE,
  updated_date TIMESTAMP WITH TIME ZONE,
  cxd_created_date DATE,
  cxd_updated_date DATE,
  CONSTRAINT bi_mrm_product_details_osc_pk PRIMARY KEY ("ID")
);