CREATE TABLE cx_cvciq_v3.bi_mrm_prod_details_osc (
  "ID" NUMBER NOT NULL,
  last_refresh_ts TIMESTAMP,
  oscproductstatus VARCHAR2(1000 BYTE),
  productid NUMBER,
  productname VARCHAR2(1000 BYTE),
  glid VARCHAR2(1000 BYTE),
  productlevel VARCHAR2(1000 BYTE),
  productclass VARCHAR2(1000 BYTE),
  productpillar VARCHAR2(1000 BYTE),
  productline VARCHAR2(1000 BYTE),
  productgroup VARCHAR2(1000 BYTE),
  mrmproductstatus VARCHAR2(1000 BYTE),
  marketableflag VARCHAR2(1000 BYTE),
  startdate TIMESTAMP WITH TIME ZONE,
  enddate TIMESTAMP WITH TIME ZONE,
  replacementproduct VARCHAR2(1000 BYTE),
  responsechannel VARCHAR2(1000 BYTE),
  adminnotes VARCHAR2(1000 BYTE),
  gtmpropername VARCHAR2(1000 BYTE),
  gtmappfamily VARCHAR2(1000 BYTE),
  gtmucmtier1 VARCHAR2(1000 BYTE),
  gtmucmtier2 VARCHAR2(1000 BYTE),
  gtmoldname VARCHAR2(1000 BYTE),
  wordmapparentid VARCHAR2(1000 BYTE),
  wordmapwordsetid VARCHAR2(1000 BYTE),
  wordmapphrasetxt VARCHAR2(1000 BYTE),
  productowned VARCHAR2(1000 BYTE),
  accountflags VARCHAR2(1000 BYTE),
  paidsearchwords VARCHAR2(1000 BYTE),
  arprkeywords VARCHAR2(1000 BYTE),
  topicscoring VARCHAR2(1000 BYTE),
  salescalcategory1 VARCHAR2(1000 BYTE),
  salescalcategory2 VARCHAR2(1000 BYTE),
  creationdate TIMESTAMP WITH TIME ZONE,
  updateddate TIMESTAMP WITH TIME ZONE,
  cxd_created_date DATE,
  cxd_updated_date DATE,
  unique_id VARCHAR2(256 BYTE),
  is_active CHAR(256 BYTE),
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  tenant_id NUMBER,
  CONSTRAINT bi_mrm_prod_details_osc_pk PRIMARY KEY ("ID")
);