CREATE TABLE cx_cvciq_v3.bi_request_topic_activity (
  "ID" NUMBER NOT NULL,
  request_activity_day_id NUMBER,
  duration NUMBER,
  room NUMBER,
  request_type_activity_id NUMBER,
  topic VARCHAR2(4000 BYTE),
  sub_topic VARCHAR2(256 BYTE),
  optional_topic VARCHAR2(4000 BYTE),
  notes_old VARCHAR2(4000 BYTE),
  unique_id VARCHAR2(256 BYTE),
  tenant_id NUMBER,
  created_by VARCHAR2(256 BYTE),
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  attribute_info VARCHAR2(20 BYTE),
  no_of_attendees NUMBER(5),
  created_ts TIMESTAMP,
  updated_ts TIMESTAMP,
  activity_start_time TIMESTAMP,
  request_id NUMBER,
  activity_date DATE,
  cvc_id NUMBER,
  notes CLOB,
  mrm_product_code VARCHAR2(256 BYTE),
  topic_type NUMBER,
  CONSTRAINT bi_request_topic_type_fk FOREIGN KEY (topic_type) REFERENCES cx_cvciq_v3.bi_topic_type ("ID")
);