CREATE TABLE cx_cvciq_v3.bi_request_presenter (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  first_name VARCHAR2(256 BYTE),
  last_name VARCHAR2(256 BYTE),
  title VARCHAR2(256 BYTE),
  email_id VARCHAR2(256 BYTE),
  is_active CHAR(6 BYTE),
  tenant_id NUMBER,
  created_ts TIMESTAMP,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  designation VARCHAR2(4000 BYTE),
  primary_email VARCHAR2(256 BYTE),
  secondary_email VARCHAR2(256 BYTE),
  presenter_type VARCHAR2(20 BYTE),
  bi_request_topic_activity_id NUMBER,
  request_type_activity_id NUMBER,
  status VARCHAR2(20 BYTE),
  presenter_order NUMBER,
  temp_presenter_id NUMBER,
  CONSTRAINT bi_request_presenter_pk PRIMARY KEY ("ID")
);