CREATE TABLE cx_cvciq_v3.bi_tenant_account (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  account_name VARCHAR2(256 BYTE),
  contact_name VARCHAR2(256 BYTE),
  contact_email VARCHAR2(256 BYTE),
  contact_phone VARCHAR2(256 BYTE),
  address1 VARCHAR2(256 BYTE),
  address2 VARCHAR2(256 BYTE),
  city VARCHAR2(256 BYTE),
  "STATE" VARCHAR2(256 BYTE),
  country VARCHAR2(256 BYTE),
  geo_location VARCHAR2(256 BYTE),
  is_active CHAR(256 BYTE),
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  tenant_id NUMBER,
  zipcode VARCHAR2(256 BYTE),
  industry_type VARCHAR2(256 BYTE),
  "TIER" VARCHAR2(20 BYTE),
  gcp_code VARCHAR2(256 BYTE),
  parent_id NUMBER,
  CONSTRAINT bi_tenant_account_pk PRIMARY KEY ("ID"),
  CONSTRAINT bi_tenant_account_unique UNIQUE (account_name),
  CONSTRAINT bi_tenant_account_ten_id_fk FOREIGN KEY (tenant_id) REFERENCES cx_cvciq_v3.bi_tenant ("ID"),
  CONSTRAINT bi_tenant_parent_fk FOREIGN KEY (parent_id) REFERENCES cx_cvciq_v3.bi_tenant_account ("ID")
);