CREATE TABLE cx_cvciq_v3.bi_template_detail (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  uri VARCHAR2(256 BYTE),
  is_active CHAR(6 BYTE),
  active_from TIMESTAMP WITH LOCAL TIME ZONE,
  active_to TIMESTAMP WITH LOCAL TIME ZONE,
  tenant_id NUMBER,
  template_master_id NUMBER,
  created_by VARCHAR2(256 BYTE),
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  "VERSION" NUMBER,
  "NAME" VARCHAR2(256 BYTE),
  subject VARCHAR2(256 BYTE),
  template_content_type VARCHAR2(20 BYTE),
  description VARCHAR2(256 BYTE),
  "CONTENT" CLOB,
  location_id NUMBER,
  CONSTRAINT bi_template_detail_pk PRIMARY KEY ("ID"),
  CONSTRAINT bi_template_detail_unique UNIQUE (template_master_id,"NAME",location_id),
  CONSTRAINT bi_template_detail_location_fk FOREIGN KEY (location_id) REFERENCES cx_cvciq_v3.bi_location ("ID"),
  CONSTRAINT bi_temp_detail_tenid_fk FOREIGN KEY (tenant_id) REFERENCES cx_cvciq_v3.bi_tenant ("ID")
);