CREATE TABLE cx_cvciq_v3.bi_tenant_account_stage (
  "ID" NUMBER,
  unique_id VARCHAR2(256 BYTE),
  account_name VARCHAR2(256 BYTE),
  contact_name VARCHAR2(256 BYTE),
  contact_email VARCHAR2(256 BYTE),
  contact_phone VARCHAR2(256 BYTE),
  address1 VARCHAR2(256 BYTE),
  address2 VARCHAR2(256 BYTE),
  city VARCHAR2(256 BYTE),
  "STATE" VARCHAR2(256 BYTE),
  country VARCHAR2(256 BYTE),
  geo_location VARCHAR2(256 BYTE),
  is_active CHAR(256 BYTE),
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  tenant_id NUMBER,
  zipcode VARCHAR2(256 BYTE),
  industry_type VARCHAR2(256 BYTE),
  "TIER" VARCHAR2(20 BYTE)
);