CREATE TABLE cx_cvciq_v3.bi_topic (
  "ID" NUMBER NOT NULL,
  unique_id VARCHAR2(256 BYTE),
  code VARCHAR2(256 BYTE),
  "NAME" VARCHAR2(256 BYTE),
  description VARCHAR2(256 BYTE),
  tenant_id NUMBER,
  topic_type_id NUMBER,
  parent_id NUMBER,
  asset_detail_id NUMBER,
  additional_info NVARCHAR2(2000),
  is_active CHAR(256 BYTE),
  created_ts TIMESTAMP WITH LOCAL TIME ZONE,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP WITH LOCAL TIME ZONE,
  updated_by VARCHAR2(256 BYTE),
  "VERSION" NUMBER,
  location_id NUMBER,
  mrm_product_name VARCHAR2(2000 BYTE),
  mrm_product_code VARCHAR2(256 BYTE),
  CONSTRAINT bi_topic_pk PRIMARY KEY ("ID"),
  CONSTRAINT bi_topic_unique UNIQUE (topic_type_id,"NAME",parent_id,location_id),
  CONSTRAINT bi_topic_location_fk FOREIGN KEY (location_id) REFERENCES cx_cvciq_v3.bi_location ("ID"),
  CONSTRAINT bi_topic_tenant_id_fk FOREIGN KEY (tenant_id) REFERENCES cx_cvciq_v3.bi_tenant ("ID"),
  CONSTRAINT bi_topic_top_typ_id_fk FOREIGN KEY (topic_type_id) REFERENCES cx_cvciq_v3.bi_topic_type ("ID")
);