CREATE TABLE cx_cvciq_v3.t_api_method (
  "ID" NUMBER(11) NOT NULL,
  unique_id VARCHAR2(128 BYTE),
  friendly_name VARCHAR2(256 BYTE),
  description VARCHAR2(512 BYTE),
  "TYPE" VARCHAR2(256 BYTE),
  account_consent_msg VARCHAR2(256 BYTE),
  account_consent_msg_order NUMBER(11),
  detailed_consent_message_id NUMBER(11),
  requires_access_token NUMBER(11),
  is_public NUMBER(11),
  api_group_id NUMBER(11),
  created_ts TIMESTAMP,
  created_by VARCHAR2(256 BYTE),
  updated_ts TIMESTAMP,
  updated_by VARCHAR2(256 BYTE),
  consent_message_id NUMBER(11),
  idx_token VARCHAR2(8 BYTE),
  CONSTRAINT t_api_method_pk PRIMARY KEY ("ID"),
  CONSTRAINT api_met_api_group_id FOREIGN KEY (api_group_id) REFERENCES cx_cvciq_v3.t_api_group ("ID")
);