CREATE OR REPLACE TRIGGER cx_cvciq_v3."BI_LOCATION_CALENDAR_TRIGGER" 
 BEFORE INSERT ON cx_cvciq_v3.BI_LOCATION_CALENDAR
 FOR EACH ROW
BEGIN
 SELECT BI_LOCATION_CALENDER_SEQ.nextval
 INTO :new.id
 FROM dual;
END;
/