CREATE OR REPLACE TRIGGER cx_cvciq_v3."BI_ROLE_TRANS_RULES_TRIGGER"
BEFORE INSERT ON cx_cvciq_v3.BI_ROLE_TRANS_RULES
FOR EACH ROW
BEGIN
SELECT BI_ROLE_TRANS_RULES_SEQ.NEXTVAL
INTO :new.id
FROM dual;
END;
/