CREATE OR REPLACE TRIGGER cx_cvciq_v3."BI_ROLE_DATA_ACCESS_MAP_TRIG" 
 BEFORE INSERT ON cx_cvciq_v3.BI_ROLE_DATA_ACCESS_MAP
 FOR EACH ROW
BEGIN
 SELECT BI_ROLE_DATA_ACC_MAP_SEQ.NEXTVAL
 INTO :new.id
 FROM dual;
END;
/