CREATE OR REPLACE TRIGGER cx_cvciq_v3."BI_TEMPLATE_VARIABLE_TRIGGER" 
 BEFORE INSERT ON cx_cvciq_v3.BI_TEMPLATE_VARIABLE
 FOR EACH ROW
BEGIN
 SELECT BI_TEMPLATE_VARIABLES_SEQ.nextval
 INTO :new.id
 FROM dual;
END;
/