CREATE OR REPLACE FORCE VIEW cx_cvciq_v3.vw_cvc_request (acquired_from,ac_id,agenda_status_id,alternative_date,alter_date,any_executive,business_case,cancelation_reason,catering,client_event,client_region,closed_revenue,close_date,company_address,company_city,company_country,company_facility,company_industry,company_name,company_phone,company_state,company_web,competitors,confirmed_date,cost_center,country,created_by,created_date,customer_id,customer_objective,desire_outcome,dress_code,duration,edr_choice,effort_level,end_time,event_focus,executive_name,file_name,file_upload_date,gift_how_many,gift_type,heading_menu,host_attending,host_fax,host_mobile,host_email,host_full_name,hotel,how_many,html_type,"ID",interpreter,it_initiatives,location_id,meeting_name,meeting_objetives,mime_type,need_breakout,not_oracle_2000,nro_ext_attendees,nro_ora_attendees,onsite_cont_name,opened_date,opportunity_revenue,opportunity_size,opportunity_status,opp_number,oracle_2000,oracle_2000_tier,oracle_500,oracle_senior_attendees,"ORGANIZATION",parent_id,partner_host,partner_pass,percentage_done,requestor_id,req_first_name,req_last_name,req_type,revenue,room_id,room_note,room_setup,sales_cycle,sales_division,sensitive_issues,service_required,special_items,start_date,start_time,status_id,status_name,sub_account,technical_setup,transportation,updated_by,updated_date,vcn,vcn_mobile,visit_classification,visit_focus,visit_summary,visit_type,digital_signage,industry) AS
select ACQUIRED_FROM,
LOWER(AC_ID) AC_ID,
AGENDA_STATUS_ID,
ALTERNATIVE_DATE,
ALTER_DATE,
ANY_EXECUTIVE,
BUSINESS_CASE,
CANCELATION_REASON,
CATERING,
CLIENT_EVENT,
CLIENT_REGION,
CLOSED_REVENUE,
CLOSE_DATE,
COMPANY_ADDRESS,
COMPANY_CITY,
COMPANY_COUNTRY,
COMPANY_FACILITY,
COMPANY_INDUSTRY,
COMPANY_NAME,
COMPANY_PHONE,
COMPANY_STATE,
COMPANY_WEB,
COMPETITORS,
CONFIRMED_DATE,
NVL(COST_CENTER,'---') COST_CENTER,
COUNTRY,
CREATED_BY,
CREATED_DATE,
CUSTOMER_ID,
CUSTOMER_OBJECTIVE,
DESIRE_OUTCOME,
DRESS_CODE,
DURATION,
EDR_CHOICE,
EFFORT_LEVEL,
END_TIME,
EVENT_FOCUS,
EXECUTIVE_NAME,
FILE_NAME,
FILE_UPLOAD_DATE,
GIFT_HOW_MANY,
GIFT_TYPE,
HEADING_MENU,
HOST_ATTENDING,
HOST_FAX,
HOST_MOBILE,
LOWER(HOST_NAME) AS HOST_EMAIL,
INITCAP(Replace(SUBSTR (host_name,1, INSTR(host_name,'@') -1),'.',' ')) as HOST_FULL_NAME,
HOTEL,
HOW_MANY,
HTML_TYPE,
ID,
INTERPRETER,
IT_INITIATIVES,
LOCATION_ID,
MEETING_NAME,
MEETING_OBJETIVES,
MIME_TYPE,
NEED_BREAKOUT,
NOT_ORACLE_2000,
NVL(NRO_EXT_ATTENDEES,1) NRO_EXT_ATTENDEES,
NVL(NRO_ORA_ATTENDEES,1) NRO_ORA_ATTENDEES,
ONSITE_CONT_NAME,
OPENED_DATE,
OPPORTUNITY_REVENUE,
OPPORTUNITY_SIZE,
OPPORTUNITY_STATUS,
OPP_NUMBER,
ORACLE_2000,
ORACLE_2000_TIER,
ORACLE_500,
ORACLE_SENIOR_ATTENDEES,
ORGANIZATION,
PARENT_ID,
PARTNER_HOST,
PARTNER_PASS,
PERCENTAGE_DONE,
LOWER(REQUESTOR_ID) REQUESTOR_ID,
REQ_FIRST_NAME,
REQ_LAST_NAME,
REQ_TYPE,
REVENUE,
ROOM_ID,
ROOM_NOTE,
ROOM_SETUP,
SALES_CYCLE,
SALES_DIVISION,
SENSITIVE_ISSUES,
SERVICE_REQUIRED,
SPECIAL_ITEMS,
START_DATE,
START_TIME,
STATUS_ID,
(SELECT DESCRIPTION FROM cx_cvc.CVC_STATUS WHERE ID = STATUS_ID) AS STATUS_NAME,
SUB_ACCOUNT,
TECHNICAL_SETUP,
TRANSPORTATION,
UPDATED_BY,
UPDATED_DATE,
VCN,
VCN_MOBILE,
VISIT_CLASSIFICATION,
VISIT_FOCUS,
VISIT_SUMMARY,
VISIT_TYPE,
DECODE(HTML_TYPE, 'FULL' , 'FULL_AGENDA' , 'NOAGENDA' , 'WELCOME', 'LOGO', 'ORACLE_LOGO','WELCOME') as DIGITAL_SIGNAGE,

(select c.industry from cx_cvc.cvc_customer c where id = customer_id) as INDUSTRY
from cx_cvc.cvc_request WHERE LOCATION_ID = 80;